### ISSUE TITLE
Increased CPF contribution rates from 1 January 2023

### ISSUE THREAD

**Issue by Liminghui86** [payrollhero/singapore_cpf_calculator#12]
<img width="557" alt="Screenshot 2022-10-28 at 3 29 25 PM" src="https://user-images.githubusercontent.com/864876/198529512-c4cb9101-462e-45e4-9f0c-b01c35eaa9c2.png">

There is an increase in the CPF contribution rate from 1 January 2023. Will this be updated? :)

**Comment by mathieujobin** [comment]
Would you care reviewing the numbers in #13 ?

**Comment by mathieujobin** [comment]
its under testing. Good luck
