### ISSUE TITLE
Cap for total and employee contributions

### ISSUE THREAD

**Issue by n3v3rf411** [payrollhero/singapore_cpf_calculator#3]
The calculator doesn't seem to take into account capping the total and employee contributions. These values change per employee/employer contribution type, and SPR status.

**Comment by more-ron** [comment]
Thanks @n3v3rf411. Could you issue a test scenario when the calculator fails?

If I remember it right we do cover the ordinary wages cap. We know about the yearly cap for additional wages but we haven't got into adding support for. Our production use cases haven't hit the need yet.

**Comment by mathieujobin** [comment]
please reopen with a test case reproducing the problem
